
// State
let questions = [];
let currentQuestionIndex = 0;
let score = 0;
let userAnswers = []; // To track history if needed later

// DOM Elements
const startScreen = document.getElementById('start-screen');
const quizContainer = document.getElementById('quiz-container');
const resultsScreen = document.getElementById('results-screen');
const startBtn = document.getElementById('start-btn');
const totalQuestionsCountEl = document.getElementById('total-questions-count');

const questionText = document.getElementById('question-text');
const optionsContainer = document.getElementById('options-container');
const feedbackContainer = document.getElementById('feedback-container');
const feedbackHeader = document.getElementById('feedback-header');
const rationaleText = document.getElementById('rationale-text');
const nextBtn = document.getElementById('next-btn');

const questionProgressEl = document.getElementById('question-progress');
const scoreDisplayEl = document.getElementById('score-display');
const progressBarFill = document.getElementById('progress-bar-fill');

const finalScoreEl = document.getElementById('final-score');
const finalStatsEl = document.getElementById('final-stats');

const questionCountInput = document.getElementById('question-count');

// Fetch Questions
async function loadQuestions() {
    try {
        const response = await fetch('/practice_questions.json'); // This file is generated by our node script
        const data = await response.json();

        // Randomize questions
        questions = shuffleArray(data);

        // Update UI info
        totalQuestionsCountEl.textContent = questions.length;

        // Update input max
        if (questionCountInput) {
            questionCountInput.max = questions.length;
            questionCountInput.value = questions.length;
        }

        // Enforce max on input
        questionCountInput.addEventListener('input', () => {
            if (parseInt(questionCountInput.value) > questions.length) {
                questionCountInput.value = questions.length;
            }
        });

        startBtn.disabled = false;

    } catch (error) {
        console.error('Failed to load questions:', error);
        totalQuestionsCountEl.textContent = 'Error loading questions.';
        totalQuestionsCountEl.classList.add('text-red-500');
    }
}

// Start Exam
startBtn.addEventListener('click', () => {
    // Limit questions based on input
    const limit = parseInt(questionCountInput.value);
    if (!isNaN(limit) && limit > 0) {
        questions = questions.slice(0, limit);
    }

    startScreen.classList.add('hidden');
    quizContainer.classList.remove('hidden');
    loadQuestion(currentQuestionIndex);
});

// Load a single question
function loadQuestion(index) {
    const question = questions[index];

    // Reset UI
    feedbackContainer.classList.add('hidden');
    optionsContainer.innerHTML = '';
    nextBtn.onclick = null; // Clear previous listener logic

    // Update Text
    questionText.textContent = question.text;

    // Update Progress
    questionProgressEl.textContent = `Question ${index + 1} of ${questions.length}`;
    const progressPercent = ((index) / questions.length) * 100;
    progressBarFill.style.width = `${progressPercent}%`;

    // Randomize Options but keep track of which is correct
    // The JSON has { label: 'A', text: '...' } and correctAnswer: 'A'
    // We need to map the "label" to the actual text to compare
    const correctOptionText = question.options.find(o => o.label === question.correctAnswer).text;

    // Shuffle options for display
    const shuffledOptions = shuffleArray([...question.options]);

    shuffledOptions.forEach(opt => {
        const btn = document.createElement('button');
        btn.className = `
            w-full text-left p-4 rounded-xl border border-gray-700 bg-gray-800/50 
            hover:bg-gray-800 hover:border-gray-600 transition-all duration-200
            flex items-start gap-3 group
        `;

        // Check circle icon
        const icon = document.createElement('div');
        icon.className = `
            w-6 h-6 rounded-full border-2 border-gray-600 flex-shrink-0 mt-0.5
            group-hover:border-blue-500 transition-colors flex items-center justify-center
        `;
        // Inner dot (hidden by default)
        icon.innerHTML = `<div class="w-3 h-3 bg-blue-500 rounded-full opacity-0 transition-opacity"></div>`;

        const textParam = document.createElement('div');
        textParam.className = 'text-gray-300 font-medium';
        textParam.textContent = opt.text;

        btn.appendChild(icon);
        btn.appendChild(textParam);

        // Click Handler
        btn.addEventListener('click', () => handleAnswer(btn, opt, question, correctOptionText));

        optionsContainer.appendChild(btn);
    });
}

function handleAnswer(selectedBtn, selectedOpt, question, correctOptionText) {
    // Disable all buttons to prevent double answers
    const allBtns = optionsContainer.querySelectorAll('button');
    allBtns.forEach(b => b.disabled = true);

    const isCorrect = selectedOpt.text === correctOptionText;

    // Visual feedback on the buttons
    if (isCorrect) {
        score++;
        scoreDisplayEl.textContent = `Score: ${score}`;
        styleButton(selectedBtn, 'correct');
    } else {
        styleButton(selectedBtn, 'incorrect');
        // Find and highlight real correct answer
        allBtns.forEach(btn => {
            if (btn.textContent.includes(correctOptionText)) {
                styleButton(btn, 'correct');
            }
        });
    }

    // Show Rationale / Feedback
    showFeedback(isCorrect, question.rationale);
}

function styleButton(btn, type) {
    btn.classList.remove('hover:bg-gray-800', 'hover:border-gray-600');
    const icon = btn.querySelector('div:first-child'); // The circle container
    const innerDot = icon.querySelector('div');

    if (type === 'correct') {
        btn.classList.add('bg-green-900/20', 'border-green-500');
        icon.classList.add('border-green-500', 'bg-green-900/20');
        icon.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-green-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>`;
    } else {
        btn.classList.add('bg-red-900/20', 'border-red-500', 'opacity-70');
        icon.classList.add('border-red-500');
        icon.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-red-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>`;
    }
}

function showFeedback(isCorrect, rationale) {
    feedbackContainer.classList.remove('hidden');

    if (isCorrect) {
        feedbackHeader.innerHTML = `
            <span class="text-green-500 flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>
                Correct!
            </span>
        `;
    } else {
        feedbackHeader.innerHTML = `
            <span class="text-red-500 flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
                Incorrect
            </span>
        `;
    }

    rationaleText.innerText = rationale || "No rationale provided.";

    // Configure Next Button
    nextBtn.onclick = () => {
        currentQuestionIndex++;
        if (currentQuestionIndex < questions.length) {
            loadQuestion(currentQuestionIndex);
        } else {
            showResults();
        }
    };
}

function showResults() {
    quizContainer.classList.add('hidden');
    resultsScreen.classList.remove('hidden');

    const percentage = Math.round((score / questions.length) * 100);
    finalScoreEl.textContent = `${percentage}%`;

    // Choose color for score
    if (percentage >= 80) finalScoreEl.className = "text-6xl font-black text-green-500 mb-2";
    else if (percentage >= 60) finalScoreEl.className = "text-6xl font-black text-yellow-500 mb-2";
    else finalScoreEl.className = "text-6xl font-black text-red-500 mb-2";

    finalStatsEl.textContent = `${score} out of ${questions.length} questions correct`;
}


// Utility: Fisher-Yates Shuffle
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Initial Load
loadQuestions();
